#!/usr/bin/env python3

##
## EPITECH PROJECT, 2019
## Untitled (Workspace)
## File description:
## bombyx.py
##

from sys import argv, stderr

def display_help():
    print("USAGE")
    print("           ./106bombyx n [k | i0 i1]\n")
    print("DESCRIPTION")
    print("           n    number of first generation individuals")
    print("           k    growth rate from 1 to 4")
    print("           i0   initial generation (included)")
    print("           i1   final generation (included)")

def execute_gen():
    
    k = 100
    i = 1

    while k <= 400:

        i = 1
        arg = float(argv[1])
        while i < int(argv[2]):
            arg = (k / 100) * arg * (1000 - arg) / 1000
            if arg < 0:
                arg = 0
            i = i + 1

        while i <= int(argv[3]):
            if (float(str("%.1f" % (arg))) == round(arg, 2)):
                print("%.2f" % (k / 100) + " " + str(round(arg, 2)) + "0")
            else:
                print("%.2f" % (k / 100) + " " + str(round(arg, 2)))
            arg = (k / 100) * arg * (1000 - arg) / 1000
            if arg < 0:
                arg = 0
            i = i + 1
        k += 1
    return 0
            

def execute_norm():

    i = 1

    arg = float(argv[1])
    while i <= 100:
        print("%d %.2f" %(i, arg))
        arg = float(argv[2]) * arg * ((1000 - arg) / 1000)
        if arg < 0:
            arg = 0
        i = i + 1
    return 0

def error ():
    if len(argv) < 2:
        print("ERROR")
        exit(84)
    if argv[1] == "-h":
        if len(argv) == 2:
            display_help()
            exit(0)
        else:
            print("ERROR")
            exit(84)
    if len(argv) == 2:
        print("ERROR")
        exit(84)
    if len(argv) >= 5:
        print("ERROR")
        exit(84)
    if len(argv) == 3:
        try:
            int(argv[1])
            float(argv[2])
        except Exception as error:
            print(error, file=stderr)
            exit(84)
        if int(argv[1]) <= 0:
            print("ERROR")
            exit(84)
        if float(argv[2]) < 1 or float(argv[2]) > 4:
            print("ERROR")
            exit(84)
    if len(argv) == 4:
        try:
            int(argv[1])
            int(argv[2])
            int(argv[3])
        except Exception as error:
            print(error, file=stderr)
            exit(84)
        if (int(argv[2]) > int(argv[3])):
            print("ERROR")
            exit(84)
        if (int(argv[1]) < 0):
            print("ERROR")
            exit(84)

if __name__=="__main__":
    error()
    if len(argv) == 3:
        execute_norm()
    if len(argv) == 4:
        execute_gen()